'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),root=path.resolve(__dirname,'..');let failed=0;
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
function ok(v,m){console.log((v?'PASS ':'FAIL ')+m);if(!v)failed++}
const pages=['closed-beta.html','founding-creators.html','join-beta.html','waitlist.html','feedback.html','creator-launch.html','beta-admin.html','beta-explore.html','beta-creator.html'];
for(const page of pages){const h=read(page);ok(/name="viewport"/.test(h),page+' viewport');ok(/<h1[ >]/.test(h),page+' h1');ok(!/href="#"/.test(h),page+' no placeholder links');ok(/beta\.js/.test(h),page+' beta utilities');for(const m of h.matchAll(/(?:href|src)="([^"#?]+)"/g)){const t=m[1];if(!/^(https?:|mailto:|tel:|data:)/.test(t))ok(fs.existsSync(path.join(root,t)),page+' target '+t)}}
for(const page of ['closed-beta.html','founding-creators.html','waitlist.html']){const h=read(page);ok(/rel="canonical"/.test(h),page+' canonical');ok(/property="og:title"/.test(h),page+' Open Graph')}
const js=read('beta.js');new vm.Script(js);for(const e of ['landing_view','explore_view','creator_profile_view','creator_application_started','creator_application_submitted','member_signup_started','member_signup_completed','invite_link_opened','content_preview_opened'])ok(js.includes("'"+e+"'"),'event '+e);for(const k of ['utm_source','utm_medium','utm_campaign','utm_content','utm_term'])ok(js.includes("'"+k+"'"),'UTM '+k);
const sql=read('setup_closed_beta.sql');for(const role of ['member','creator','admin'])ok(sql.includes("'"+role+"'"),'role '+role);for(const fn of ['submit_creator_application','validate_beta_invitation','approve_creator_application','create_beta_invitation','join_beta_waitlist','submit_beta_feedback','track_beta_event','get_beta_admin_dashboard'])ok(sql.includes('function public.'+fn),'RPC '+fn);for(const t of ['user_balances','deposits','purchases','subscriptions','payouts','products'])ok(sql.includes("'"+t+"'"),'finance lock '+t);ok(/revoke insert, update, delete, truncate/.test(sql),'browser financial writes revoked');
const betaCode=pages.map(read).join('\n');ok(!/user_balances|from\(["'](?:deposits|payouts|purchases|subscriptions)["']/.test(betaCode),'beta routes have no financial data path');const legacy=fs.readdirSync(root).filter(f=>/\.html$/.test(f)&&/from\(["'](?:user_balances|deposits|payouts|purchases)["']\)\.(?:insert|update|delete)/.test(read(f)));ok(legacy.length>0,'scanner detects blocked legacy finance: '+legacy.join(', '));ok(fs.existsSync(path.join(root,'robots.txt'))&&fs.existsSync(path.join(root,'sitemap.xml')),'crawler files exist');
if(failed){console.error(failed+' checks failed');process.exit(1)}console.log('All beta readiness static checks passed.');
